app:
  version_check_url: "https://raw.githubusercontent.com/sansan0/TrendRadar/refs/heads/master/version"
  show_version_update: true # 控制显示版本更新提示，改成 false 将不接受新版本提示

crawler:
  request_interval: 1000 # 请求间隔(毫秒)
  enable_crawler: true # 是否启用爬取新闻功能，false 时直接停止程序
  use_proxy: false # 是否启用代理，false 时为关闭
  default_proxy: "http://127.0.0.1:10086"

# 🔸 daily（当日汇总模式）
#   • 推送时机：按时推送
#   • 显示内容：当日所有匹配新闻 + 新增新闻区域
#   • 适用场景：日报总结、全面了解当日热点趋势
#
# 🔸 current（当前榜单模式）
#   • 推送时机：按时推送
#   • 显示内容：当前榜单匹配新闻 + 新增新闻区域
#   • 适用场景：实时热点追踪、了解当前最火的内容
#
# 🔸 incremental（增量监控模式）
#   • 推送时机：有新增才推送
#   • 显示内容：新出现的匹配频率词新闻
#   • 适用场景：避免重复信息干扰

report:
  mode: "daily" # 可选: "daily"|"incremental"|"current"
  rank_threshold: 5 # 排名高亮阈值

notification:
  enable_notification: true # 是否启用通知功能，false 时不发送手机通知
  message_batch_size: 4000 # 消息分批大小（字节）(这个配置别动)
  batch_send_interval: 1 # 批次发送间隔（秒）
  feishu_message_separator: "━━━━━━━━━━━━━━━━━━━" # feishu 消息分割线

  webhooks:
    feishu_url: "" # 飞书机器人的 webhook URL
    dingtalk_url: "" # 钉钉机器人的 webhook URL
    wework_url: "" # 企业微信机器人的 webhook URL
    telegram_bot_token: "" # Telegram Bot Token
    telegram_chat_id: "" # Telegram Chat ID

# 用于让关注度更高的新闻在更前面显示，合起来是 1 就行
weight:
  rank_weight: 0.6 # 排名权重
  frequency_weight: 0.3 # 频次权重
  hotness_weight: 0.1 # 热度权重

platforms:
# 科技
  - id: "v2ex"
    name: "V2EX 最新分享"
  - id: "coolapk"
    name: "酷安 今日最热"
  - id: "ithome"
    name: "IT之家"
  - id: "pcbeta"
    name: "远景论坛 Windows 11"
  - id: "solidot"
    name: "Solidot"
  - id: "ycombinator"
    name: "Hacker News"
  - id: "producthunt"
    name: "Product Hunt"
  - id: "github"
    name: "Github Today"
  - id: "sspai"
    name: "少数派"
  - id: "juejin"
    name: "稀土掘金"
# 国内
  - id: "zhihu"
    name: "知乎"
  - id: "weibo"
    name: "微博 实时热搜"
  - id: "douyin"
    name: "抖音"
  - id: "hupu"
    name: "虎扑 主干道热帖"
  - id: "baidu"
    name: "百度贴吧 热议"
  - id: "toutiao"
    name: "今日头条"
  - id: "thepaper"
    name: "澎湃新闻 热榜"
  - id: "bilibili"
    name: "哔哩哔哩 热榜"
  - id: "baidu"
    name: "百度热搜"
  - id: "nowcoder"
    name: "牛客"
  - id: "ifeng"
    name: "凤凰网 热点资讯"
  - id: "chongbuluo"
    name: "虫部落 最热"
  - id: "chongbuluo"
    name: "虫部落 最新"
# 国际
  - id: "zaochenbao"
    name: "联合早报"
  - id: "sputniknews"
    name: "卫星通讯社"
  - id: "ckxxapp"
    name: "参考信息"
  - id: "kyodonews"
    name: "靠谱新闻"
# 财经
  - id: "mktnews"
    name: "MKTNews 快讯"
  - id: "wallstreetcn"
    name: "华尔街实时快讯"
  - id: "wallstreetcn"
    name: "华尔街最新资讯"
  - id: "wallstreetcn"
    name: "华尔街最热文章"
  - id: "cls"
    name: "财联社 电报"
  - id: "cls"
    name: "财联社 深度"
  - id: "cls"
    name: "财联社 热门"
  - id: "xueqiu"
    name: "雪球 热门股票"
  - id: "fastbull"
    name: "格隆汇 事件"
  - id: "fastbull"
    name: "法布财经 快讯"
  - id: "fastbull"
    name: "法布财经 头条"
  - id: "flash"
    name: "金十数据"
